name: Kernel Build                                    
on:
  push:
    branches:
      - main  

jobs:                                                   
  build:
    runs-on: ubuntu-latest
    steps:                                                  
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential flex bison libssl-dev bc gcc-arm-linux-gnueabi

      - name: Download Linux Kernel Source
        run: |
          git clone --depth=1 https://github.com/torvalds/linux.git kernel_source

      - name: Configure Kernel
        run: |
          cd kernel_source
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- defconfig  

      - name: Compile Kernel
        run: |
          cd kernel_source
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- -j$(nproc)

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-kernel
          path: kernel_source/arch/arm/boot/Image

      - name: Release Kernel
        uses: softprops/action-gh-release@v1
        with:
          files: kernel_source/arch/arm/boot/Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
